### ISSUE TITLE
Feature Request: Reinstate Original Sound Prompts in WlanReporter

### ISSUE THREAD

**Issue by cary-rowen** [kefaslungu/resourceMonitor#20]
Hello,

I extend my appreciation for the invaluable work you do in consistently enhancing this project. A recent update caught my attention, wherein the functionality of the WlanReporter was introduced in the Resource Monitor add-on. While I commend this integration, I believe there is room for some improvement.

Upon the introduction of WlanReporter, the original sound prompt files were substituted with longer ones. This alteration has led to some dissatisfaction among the user community on Groups.io, primarily due to the lengthiness of the new sound files. Interestingly, there was no previous feedback indicating any disturbance caused by the original sound cues of the WlanReporter.

In light of this, could we consider reinstating the original sound prompts of the WlanReporter? The utility of these auditory signals cannot be understated, particularly when abrupt network disconnections or connections occur. These prompts provide users with an immediate and effective way of monitoring their network status, eliminating the need for manual checks.

Thank you for considering this request. Your continuous commitment to user experience refinement is greatly appreciated.

Best regards,
Cary

**Comment by cary-rowen** [comment]
In the meantime, I'm sure people will also want you to release a fix that includes PR#19.

**Comment by kefaslungu** [comment]
hi,
the old sounds are back, and V23.06 is now available via the addon store with pr #19

**Comment by cary-rowen** [comment]
Thank you for your effort on this
