### ISSUE TITLE
Drop support for NVDA versions earlire than 2024.1 to use gettext.ngettext method for singular/plural strings properly

### ISSUE THREAD

**Issue by josephsl** [kefaslungu/resourceMonitor#27]
Hi,

This may need to be done sometime in 2024 after NVDA 2024.1compatibility version is published:

One of the biggest issues with Resource MOnitor add-on is translatable messages. Specificlaly, both singular and plural forms of messages 9hour and hours, for example) are defined because NVDA does not support gettext.ngettext. This issue is resolved in 2024.1 so singular and plural forms can be defined in one go. This necessitates droppping support for NVDA versions earlier than 2024.1.

Implementation plan:

1. Wait until NVDA 2024.1 compatible versoin is released to the stable channel.
2. After several months, revisit and implement the proposal.

Thanks.

**Comment by kefaslungu** [comment]
hi joseph, it will be well appreciated if the messages can be streamline. Thank you for your thoughtful suggestion.

**Comment by josephsl** [comment]
Hi,

March 2024 update: on March 20, 2024, NVDA 2024.1 compatible Resource monitor release was published to stable channel. I propose June 2024 release as the one requiring NVDA 2024.1 and later.

Thanks.

**Comment by kefaslungu** [comment]
Hi Joseph,

Why wait until june, isn't it too far?

**Comment by josephsl** [comment]
Hi, to give folks time to upgrade various add-ons they have. Another option is to wait until NVDA 2024.2 release since it will include psutil by default (and it will give us a reason to require 2024.2 instead). Thanks.

**Comment by josephsl** [comment]
Hi,

I think 2024.1 requirement could be ready by May 2024 (24.05) as add-on authors are making 2024.1 compatible versions available on NV Access add-on store stable channel.

Thanks.

**Comment by josephsl** [comment]
Hi,

Implemented as of 24.05. Thanks.
