### ISSUE TITLE
Proposal: remove WLAN Reporter add-on code due to inclusion of offensive comments toward specific groups or look for an alternative

### ISSUE THREAD

**Issue by josephsl** [kefaslungu/resourceMonitor#29]
Hi,

The following may or may not affect Resource Monitor 24.05:

After looking at WLAN Reporter add-on (the code included in Resource Monitor), I noticed that it derives from kvark128's code which is fine on the surface. The newer iteration of the add-on does include WPA3 constants, which is one of the highlights of Resource Monitor 24.05. However, it turns out this is one of the add-ons containing offensive comments toward specific groups. Thankfully, the version included in Resource Monitor does not contain the offensive comment (and does not contain copyright header info either).

Therefore, I propose either removing wireless network announcement from Resource Monitor, or find an alternative to WLAN Reporter code, perhaps forking that add-on code entirely or directing users to Wi-Fi Monitor add-on (recently published on add-on store). The WLAN Reporter code included in Resource Monitor 24.05 does not include offensive comment and adds WPA3 constants.

Thanks.

**Comment by cary-rowen** [comment]
I'm in favor of forking this code and keeping the user experience the same.

**Comment by kefaslungu** [comment]
hi,

if it's just comments, it could always be removed. I'll check the other addon @josephsl  was talking about.

**Comment by dangero2000** [comment]
I'm in favor of forking the code and removing the comments, but not removing the code entirely.

**Comment by josephsl** [comment]
Hi,

Revisiting this issue: I think creating a fork makes more sense - internal at first (part of the add-on), then gradually releasing it on a separate repo for use by add-ons community (won't go through typical repo fork process but will be uploaded as a new repo so it can be maintained by the community). I'll acknolwedge the original author with a comment on offensive language in the original code base.

Thanks.

**Comment by josephsl** [comment]
Hi,

By the way, the WLAN Reporter code will be subject to Ruff and transformation into Python 3.11 syntax.

Thanks.

**Comment by josephsl** [comment]
Hi,

Add-on 24.08 makes changes to wlanapi.py by mentioning geopolitical notices deemed offensive in the original source version while the one included with Resource Monitor can be used anywhere.

Tanks.

**Comment by josephsl** [comment]
Hi,

2026 update: I may need to reopen this issue as the NV Access add-on store has several wireless network connection reporting add-ons registered. Unless peole say otherwise, wireless connection routines (including wlanapi file) might be removed from this add-on in a future release.

Thanks.
