### ISSUE TITLE
Multilayer commands or virtual menu

### ISSUE THREAD

**Issue by nvda-ru** [kefaslungu/resourceMonitor#37]
Greetings addon developers.

Please add one more function to the addon without assigned gesture.
The function will open the second layer of commands (virtual panel).
Thus, it will be possible, if necessary, not to use the usual separate shortcuts, and open a layer of commands, where you can press the right key with a given number to perform the desired function.
For example, key 1, 2, 3 and up to key 0.
This will also allow you not to memorize a lot of commands addon, and remember only one to open the second layer.
Long-time addon users will be able to habitually use separate launch commands.

An example of the implementation of two different panels, there is an excellent addon ClipboardHistory.

https://github.com/GerardKessler/clipboardHistory

Thanks!

P.S..
In the Spanish addon catalog there is Resource Monitor 24.06 , but here in the revisions there is no such version.
https://nvda-addons.org/addon.php?id=19

**Comment by josephsl** [comment]
Hi,

This is more towards an NVDA issue, and an issue was already opened there regarding layered commands support (beyond the scope of this add-on at the moment, closing). Thanks.

**Comment by josephsl** [comment]
Hi,

2026 update: #68 is a mord version of this request.
