### ISSUE TITLE
consider how to make add-on available for Windows 10  21h1.

### ISSUE THREAD

**Issue by valiant8086** [kefaslungu/resourceMonitor#38]
Hi.

There are a few individuals running Windows 10 ltsc 2021 which will remain supported until 2027. If there is not something specifically broken for that version, consider making the add-on be willing to install there again. To be honest, ltsc2029 being supported until 2029 would also be something to consider, but if it's broken on either than I wouldn't bother. The question then becomes how to obtain the older add-ons that will run on those versions.

I assume they're available from the releases area here. Isn't it possible to make both available on the add-on store? Maybe the add-on store needs to update functionality so it can learn from each add-on before downloading which OS it targets and be able to filter out ones not supported on this OS. In any event, if it's possible to post another entry of the older version of the add-on, maybe even modifying the name so it says on it (windows10 compatible) or something like that.

Sometimes I think these end of support changes for the add-on might be done just to keep people consistent and encourage updating and whatnot. If there's an actual underlying breakage then cool, but if this last change was actually made just to change the minimum OS supported, well...

**Comment by josephsl** [comment]
Hi,

While we understand that LTSC is being used by some people, it is not a supported consumer-level configuration by Microsoft as LTSC is really meant for mission critical environments. This ad-on has adopted this policy recently and there is no plans to change this at this time.

Tanks.

**Comment by josephsl** [comment]
Hi,

In addition to providing the download link for the last 21H2 compatible release (which won't run properly on newer NVDA releases and will not load even on 2024.1), I can document LTSC support from the add-on in the readme just like I do with Windows App Essentials. But as for the overall answer on LTSC support, no.

Thanks.

**Comment by valiant8086** [comment]
Gotcha. Do you want this open until you have done the documentation updates? Otherwise, we can close this now.

**Comment by josephsl** [comment]
Hi,

The last version compatible with Windows 10 21H2:

https://github.com/kefaslungu/resourceMonitor/releases/download/24.04/resourceMonitor-24.04.nvda-addon

Correction to my last comment: this version will work on NVDA 2024.1. Support for future NVDA releases from 21H2 compatible releases is not guaranteed.
Thanks.

**Comment by josephsl** [comment]
Hi, closed with the link to the last compatible version provided. I’ll document this in the next version (likely tomorrow or Tuesday). Thanks.
